// AUTO-GENERATED from cl_config.py by gen_cpp_config.py -- DO NOT EDIT BY HAND
#pragma once

#define STORAGE_CAPACITY 42000
#define REINFORCE_NODE 1.0
#define DECAY_PER_TURN 0.997
#define RECENCY_TAU 12.0
#define REINFORCE_EDGE 1.0
#define PROXIMITY_WINDOW 3
#define PROXIMITY_DECAY 0.5
#define EDGE_CAPACITY_PER_NODE 96
#define STRENGTH_K 1.0
#define STRENGTH_REF 14.0
#define STRENGTH_ASSOC_MIN 0.05
#define SIM_THRESHOLD 0.25
#define COMPOSE_BONUS 0.15
#define STRENGTH_RECENCY_ENABLED 1
#define STRENGTH_RECENCY_DECAY 0.992
#define STRENGTH_IDLE_GRACE 8
#define STRENGTH_FORGET_THRESHOLD 0.5
#define INFO_W 2.0
#define STRENGTH_W 1.0
#define RECENCY_W 0.5
#define INFO_DELTA_REF 1.0
#define MATCH_THRESHOLD 0.12
#define MATCH_ASSOC_W 0.6
#define SPREAD_HOPS 4
#define SPREAD_DECAY 0.62
#define SPREAD_THRESHOLD 0.02
#define SPREAD_MAX_UNLOCK 64
#define SLEEP_COST_K 1.0
#define CONSOLIDATE_STRENGTH_MAX 2.5
#define CONSOLIDATE_BATCH 200
